PromptsLibrary = (function() {
	var initialized = false;
	var allPrompts = [];
	
	function populateAllPrompts() {
		allPrompts = [];

		allPrompts.push("What was your biggest kitchen fail?");
		allPrompts.push("What would you call your signature dance move?");
		//allPrompts.push("If you could kill off any character from a current television show, who would it be?");
		//allPrompts.push("What is the funniest name you have actually heard used in the real world?");
		allPrompts.push("What sport would be the funniest to add a mandatory amount of alcohol to?");
		allPrompts.push("If you could replace all of the grass in the world with something else, what would it be?");
		allPrompts.push("If you had to choose one animal to help you win a fight, which animal would you choose?");
		allPrompts.push("If you could morph two animals to make one super animal, what two animals would you choose?");
		allPrompts.push("What movie would be greatly improved if it was made into a musical?");
		//allPrompts.push("If you could choose one musical artist to marry but could never listen to their music again, who would it be?");
		allPrompts.push("If your five-year-old self could see you now, what would they say?");
		allPrompts.push("What is something that everyone looks stupid doing?");
		allPrompts.push("What's the worst text message to send to the wrong person?");
		allPrompts.push("What are two items you could buy together at the grocery store to make the cashier laugh?");
		//allPrompts.push("Have you ever caught something on fire while you were cooking? What?");
		allPrompts.push("What is something that is really popular now, but in 5 years everyone will look back on and be embarrassed by?");
		//allPrompts.push("What is your most embarrassing moment from high school?");
		allPrompts.push("What would be the hat to end all hats?");
		//allPrompts.push("What could you wear on your head that would make people stop what they are doing and stare?");
		//allPrompts.push("What is your favorite dance move to do when you are at the club?");
		//allPrompts.push("What would your favorite dance move be if you were at a wedding?");
		allPrompts.push("If animals could talk, which would be the rudest?");
		allPrompts.push("Which animal do you think would be the most polite?");
		allPrompts.push("In 40 years what will people be nostalgic for?");
		//allPrompts.push("What inanimate object do you wish you could eliminate from existence?");
		allPrompts.push("What is one thing that is okay to do occasionally but definitely not okay to do every day?");
		//allPrompts.push("What is the weirdest thing you have seen in someone else’s home?");
		//allPrompts.push("Who do you know that really reminds you of a character in a TV show or movie?");
		allPrompts.push("What would be the coolest animal to scale up to the size of a horse?");
		//allPrompts.push("What is the most embarrassing thing you have ever worn?");
		//allPrompts.push("If you could kill off any character from a current TV show who would it be and why?");
		//allPrompts.push("What part of a kid’s movie completely scarred you?");
		//allPrompts.push("What kid’s movie did you think was too scary when you were a child?");
		allPrompts.push("What used to be considered trashy but now is very classy?");
		allPrompts.push("If you had the power to shrink any one object and carry it with you in your pocket, which item would it be?");
		allPrompts.push("If you were arrested with no explanation, what would your friends and family assume you had done?");
		//allPrompts.push("What’s the most ridiculous fact you know?");
		allPrompts.push("What set of items could you buy that would make the cashier the most uncomfortable?");
		allPrompts.push("What items could you buy together that would make the cashier laugh?");
		//allPrompts.push("What is the funniest joke you know by heart?");
		//allPrompts.push("What are the unwritten rules of where you work?");
		allPrompts.push("What is something that you just recently realized that you are embarrassed you didn’t realize earlier?");
		//allPrompts.push("What is the funniest corporate or business screw up you have heard of?");
		//allPrompts.push("If you die and find out that everyone gets to choose a twelve-foot by twelve-foot square to stay in alone for eternity without being able to influence or contact the living world, what twelve-foot by twelve-foot square would you choose?");
		//allPrompts.push("What’s the best type of cheese?");
		allPrompts.push("If you were kind or queen for a day, what would be your first rule that you would change?");
		//allPrompts.push("What kind of cult would you like to start?");
		allPrompts.push("In one sentence, how would you sum up the internet?");
		allPrompts.push("First think of a product. Now, what would be the absolute worst brand name for one of those products?");
		//allPrompts.push("If your state was represented by food, what food would it be?");
		//allPrompts.push("What are some of the nicknames you have for customers or coworkers?");
		allPrompts.push("What would be the absolute worst name you could give your child?");
		allPrompts.push("What are some fun and interesting alternatives to war that countries could settle their differences with?");
		//allPrompts.push("What would the world be like if it was filled with male and female copies of you?");
		allPrompts.push("What’s the best Wi-Fi name you can think of?");
		allPrompts.push("If you would create a holiday, what would it be called and how would we celebrate it?");
		//allPrompts.push("If you had to give up one thing that you do every day, what would it be?");
		//allPrompts.push("If life were a video game, what would some of the cheat codes be?");
		allPrompts.push("How many chickens would it take to kill an elephant?");
		allPrompts.push("What would be the worst “buy one get one free” sale of all time?");
		//allPrompts.push("Is a hotdog a sandwich?");
		//allPrompts.push("What secret conspiracy would you like to start?");
		allPrompts.push("What would be the worst thing for the government to make illegal?");
		//allPrompts.push("Which body part do you wish you could detach and why?");
		//allPrompts.push("What’s the weirdest thing a guest has done at your house?");
		//allPrompts.push("If you had to give up either brushing your teeth or brushing your hair every day, which one would you choose?");
		allPrompts.push("What’s invisible but you wish people could see?");
		allPrompts.push("What movie completely changes its plot when you change one letter in its title? What’s the new movie about?");
		allPrompts.push("If you were a pair of shoes, what kind of shoes would you be?");
		allPrompts.push("If you were held at gunpoint and told that if you didn’t impress them with your dance moves you would be killed, what dance moves would you bust out?");
		allPrompts.push("Would you rather be a hobbit or an elf for a day? What is the first thing you would do?");
		allPrompts.push("If you had to replace your hands with something other than hands, hooks, or claws, what would you choose and why?");
		//allPrompts.push("Where is the strangest place you’ve urinated or defecated?");
		allPrompts.push("In the event of the apocalypse, what three places are you going to first to gather supplies?");
		allPrompts.push("During the apocalypse, what supplies are the most important (besides weapons and food)?If you manage to survive the apocalypse, what will your new job title be?");
		//allPrompts.push("In the apocalypse, would you rather tough it alone or try to find a community to live in?");
		//allPrompts.push("What’s the weirdest smell you have ever smelled?");
		allPrompts.push("What mythical creature would improve the world most if it existed?");
		allPrompts.push("Would you go streaking across the field at a sporting event for a thousand dollars, even if there was a 50/50 chance you could get arrested for indecent exposure?");
		//allPrompts.push("What is the silliest/most embarrassing thing you have done while drinking?");
		allPrompts.push("What is your favorite drinking game to play and why?");
		allPrompts.push("If you could have an unlimited storage space full of one thing, what would it be?");
		//allPrompts.push("How do you feel about putting pineapple on pizza?");
		//allPrompts.push("Do you fold your pizza when you eat it?");
		allPrompts.push("If you had to become an animal for a year, what object would it be?");
		allPrompts.push("If you could only eat one food item for the rest of your life, what would it be?");
		allPrompts.push("You’re a mad scientist, what scientific experiment would you run if money and ethics weren’t an issue?");
		allPrompts.push("What two totally normal things become really weird if you do them back to back?");
		allPrompts.push("If peanut butter wasn’t called peanut butter, what would it be called?");
		//allPrompts.push("If a hacker hacked into your computer and was threatening to release your browser history to your friends and family, how much would you pay them to avoid it?");
		allPrompts.push("What would be the creepiest thing you could say while passing a stranger on the street?");
		//allPrompts.push("What ridiculous and untrue, yet slightly plausible, theories can you come up with for the cause of common ailments like headaches or cavities?");
		//allPrompts.push("What’s the most imaginative insult you can come up with?");
		//allPrompts.push("If you were wrongfully put into an insane asylum, how would you convince them that you’re actually sane and not just pretending to be sane?");
		//allPrompts.push("What would be the best-worst name for different types of businesses? (dry cleaners, amusement parks, etc.)");
		allPrompts.push("If you were a street fighter, what would your theme song be?");
		allPrompts.push("If you were transported 400 years into the past, how would you prove that you were from the future?");
		//allPrompts.push("Toilet paper, over or under?");
		//allPrompts.push("What fictional character is amazing in their book / show / movie, but would be insufferable if you had to deal with them in mundane everyday situations?");
		//allPrompts.push("What are some fun ways to answer everyday questions like “how’s it going” or “what do you do”?");
		//allPrompts.push("What would some fairytales be like if they took place in the present and included modern technology and culture?");
		//allPrompts.push("Is cereal soup?");
		//allPrompts.push("If over time you replace parts on a car, at what point does it stop being the same car you bought? How many parts do you need to replace to make it a new car?");
		//allPrompts.push("If someone asked to be your apprentice and learn all that you know, what would you teach them?");
		//allPrompts.push("What’s the best inside joke you’ve been a part of?");
		//allPrompts.push("What are the three best things about you that you wouldn’t put in your bio on a dating profile?");
		//allPrompts.push("On a scale of 1-10, how strict are/were your parents?");
		//allPrompts.push("Were your parents more or less strict on you than they were your siblings?");
		//allPrompts.push("Who was your worst teacher? Why?");
		//allPrompts.push("Who was your favorite teacher? Why?");
		//allPrompts.push("Which would you pick: being world-class attractive, a genius or famous for doing something great?");
		//allPrompts.push("Who are the 3 greatest living musicians?");
		//allPrompts.push("What was your favorite toy growing up?");
		//allPrompts.push("Who is a celebrity you admire and why?");
		//allPrompts.push("What is one animal that you are really afraid of?");
		allPrompts.push("What movie completely changes its plot when you change one letter in the movie title?");
		allPrompts.push("Who is a celebrity that you think shouldn’t be famous?");
		//allPrompts.push("What accomplishment are you most proud of?");
		//allPrompts.push("Would you rather sweat melted cheese or have snakes for hair?");
		//allPrompts.push("Which of your friends are you proudest of? Why?");
		//allPrompts.push("What’s the most beautiful place you’ve ever been?");
		allPrompts.push("What mythical creature would improve the world if it existed?");
		//allPrompts.push("What are your 3 favorite movies?");
		//allPrompts.push("Would you rather have to eat a bowl full of cricket or a bowl full of worms?");
		//allPrompts.push("How would you describe me to your friends?");
		allPrompts.push("Which historical figure would you like to meet?");
		//allPrompts.push("What’s the right age to get married?");
		//allPrompts.push("Would you rather have a rare disease that makes you always say everything that is on your mind or lose the ability to ever speak again?");
		//allPrompts.push("Tell me 3 things you remember about kindergarten.");
		//allPrompts.push("What paper that you’ve written are you most proud of?");
		allPrompts.push("What would you do if you were invisible for a day?");
		allPrompts.push("Who would you like to live like for a day?");
		allPrompts.push("If you could time travel, where would you go?");
		//allPrompts.push("If you could live in any TV home, what would it be?");
		allPrompts.push("What’s the best ice cream flavor?");
		//allPrompts.push("Would you rather shoot spaghetti out of your fingers or sneeze meatballs?");
		//allPrompts.push("Would you rather live for a week in the past or the future?");
		//allPrompts.push("What’s your best childhood memory?");
		//allPrompts.push("What’s your favorite holiday?");
		//allPrompts.push("If you could eat only 3 foods for the rest of your life, what would they be?");
		allPrompts.push("If you could be a cartoon character for a week, who would you be?");
		//allPrompts.push("Would you rather have x-ray vision or the ability to always know when someone is lying to you?");
		allPrompts.push("If you could have dinner with anyone from history, who would it be?");
		//allPrompts.push("What’s one choice you really regret?");
		//allPrompts.push("What’s your favorite childhood book?");
		//allPrompts.push("What’s a great book you’ve read recently?");
		//allPrompts.push("Do you feel like a leader or a follower?");
		//allPrompts.push("If you could ask your pet 3 questions, what would they be?");
		//allPrompts.push("What’s the most courageous thing you’ve ever done?");
		//allPrompts.push("Who would play you in a movie of your life?");
		//allPrompts.push("If you could be an Olympic athlete, in what sport would you compete?");
		//allPrompts.push("If you had to live in a different state, what would it be?");
		//allPrompts.push("What living person, other than family members, do you most admire?");
		//allPrompts.push("What has been your favorite family vacation?");
		//allPrompts.push("If you could choose your own nickname, what would it be?");
		//allPrompts.push("Who is the funniest person you know?");
		//allPrompts.push("What’s your favorite thing about one of your grandparents?");
		//allPrompts.push("Tell the person to your right your favorite thing about them.");
		//allPrompts.push("Do you ever talk to yourself? When and what do you say?");
		allPrompts.push("When you’re having a bad day, what do you do to make yourself feel better?");
		//allPrompts.push("Which TV family is most like your own?");
		allPrompts.push("What’s the best smell in the whole world?");
		allPrompts.push("What do you think is the greatest invention of all time?");
		allPrompts.push("Using one word, how would you describe the host of this game?");
		//allPrompts.push("Would you rather win an Olympic medal, an Academy Award or the Nobel Peace prize?");
		//allPrompts.push("What’s your favorite time of day?");
		//allPrompts.push("What’s your favorite season?");
		allPrompts.push("What’s the worst food?");
		allPrompts.push("If you could read minds, what would you do?");
		allPrompts.push("What is the best sound in the world?");
		//allPrompts.push("What 3 famous people, living or dead, would you want at your fantasy dinner party?");
		allPrompts.push("If you could ask the President one question, what would it be?");
		//allPrompts.push("Have you ever accidentally been caught in your birthday suit?");
		//allPrompts.push("If you could pick a new first name, what would it be?");
		//allPrompts.push("If you had to leave earth on a spaceship and take 4 friends with you, who would they be?");
		//allPrompts.push("Have you ever noticed that easy open packages are actually pretty hard to open?");
		//allPrompts.push("What is your favorite movie quote?");
		//allPrompts.push("If you won a trip to anywhere in the world, where would you take me?");
		allPrompts.push("What’s your biggest pet peeve?");
		//allPrompts.push("Do you sleep with your sheets tucked in or out?");
		allPrompts.push("Do you ever count your steps when you walk?");
		//allPrompts.push("What’s your favorite kind of sandwich?");
		//allPrompts.push("What’s your dream job?");
		//allPrompts.push("Cake or pie?");
		//allPrompts.push("Who is the kindest person you know?");
		//allPrompts.push("Would you rather have noisy neighbors or nosy neighbors?");
		//allPrompts.push("What’s the best part about having siblings?");
		//allPrompts.push("What is the scariest movie you’ve ever seen?");
		//allPrompts.push("Would you rather live somewhere where it is always winter or where it is always summer?");
		//allPrompts.push("If you could travel anywhere in the world, where would it be?");
		//allPrompts.push("What is your favorite family tradition?");
		//allPrompts.push("Would you rather eat a stick of butter or snort a tablespoon of salt?");
		//allPrompts.push("Who’s your celebrity crush?");
		//allPrompts.push("What trait do you like the most about yourself?");
		//allPrompts.push("What are you good at?");
		allPrompts.push("What fictional character do you wish you could meet?");
		allPrompts.push("If you could be great at one sport which would you choose?");
		allPrompts.push("What’s the first thing you do when you get home from a trip?");
		//allPrompts.push("Would you rather spend five days exploring Disney or New York City?");
		allPrompts.push("If you had to have an extra body part, what would it be?");
		//allPrompts.push("Could you go a week without your smart phone?");
		//allPrompts.push("Whose parents do/did you wish you had?");
		allPrompts.push("If you could shop for free at one store, which one would you choose?");
		//allPrompts.push("How did you get out of being in trouble when you were a child?");
		//allPrompts.push("Have you ever been banned from a public place? If so, why?");
		//allPrompts.push("Would you rather only be able to whisper or only be able to yell everything?");
		//allPrompts.push("Did you ever skip school as a child?");
		allPrompts.push("What personal trait has gotten you in the most trouble?");
		//allPrompts.push("Which celebrity chef would you most like to fix you a meal?");
		//allPrompts.push("Who is your favorite athlete?");
		//allPrompts.push("What is the best piece of advice you’ve received?");
		//allPrompts.push("If you had to pick a new name for yourself, what name would you pick?");
		//allPrompts.push("Would you rather be the most popular kid in school or the smartest kid in school?");
		allPrompts.push("If it had to be something in the room you're in right now, what would your zombie apocalypse weapon be?");
		allPrompts.push("What's the best activity for rainy days?");
		allPrompts.push("What is the stupidest way to hurt yourself?");
		//allPrompts.push("Would you rather be the best player on a horrible team or the worst player on a great team?");
		allPrompts.push("What is your favorite animal sound?");
		
		allPrompts.push("If you could choose any animal to be your permanent sidekick, what animal would it be?");
		//allPrompts.push("What is your favorite thing about the beach?");
		allPrompts.push("If you had to suddenly flee the country, where would you go?");
		allPrompts.push("If you could be anywhere else right now, where would it be?");
		//allPrompts.push("What is your favorite Disney movie?");
		//allPrompts.push("What is the worst date you’ve ever been on and how long did it last?");
		//allPrompts.push("Which of the Seven Dwarfs is most like you?");
		//allPrompts.push("If someone made a movie of your life would it be a drama, a comedy, a romantic-comedy, action film, or science fiction?");
		allPrompts.push("How would you take down Kanye West’s ego?");
		allPrompts.push("Name a product or service you love so much that you’d happily be that company’s spokesperson.");
		//allPrompts.push("If you could choose between using a time machine to go back in time or to go into the future, which would you choose?");
		allPrompts.push("If you could use a time machine to go back into your past and fix one thing, what would it be?");
		//allPrompts.push("What is the sickest you have ever been?");
		allPrompts.push("If you were guaranteed to be successful in a different profession, what would be the best one to choose?");
		//allPrompts.push("Do you believe in ghosts and would you ever go ghost hunting?");
		//allPrompts.push("If you could be a professional at any sport, what sport would it be?");
		allPrompts.push("What crazy name would you give your child if you were a celebrity?");
		//allPrompts.push("What would you say to the President if you had the chance?");
		//allPrompts.push("How do you handle people you don’t like?");
		//allPrompts.push("If you could have a conversation with any one of our world leaders, who would it be and why?");
		//allPrompts.push("As a child, what did you wish to become when you grew up?");
		//allPrompts.push("What’s the worst thing you did as a kid?");
		allPrompts.push("What movie title best explains your life right now and why?");
		//allPrompts.push("What is the best part of being a part of your family?");
		allPrompts.push("What is the best day of the week and why?");
		//allPrompts.push("If you had to either shave your head or dye all of your hair pink, which would you choose?");
		allPrompts.push("If you could have plastic surgery to enlarge one part of you body, what would it be?");
		allPrompts.push("If you had to marry one Star Wars character, which one would you choose?");
		allPrompts.push("If you had to wear one halloween costume every day for the rest of your life, what would you be?");
		allPrompts.push("If you could be a fly on the wall, where would you land?");
		allPrompts.push("If you had to choose one cartoon character to be your best friend, what character would you choose?");
		allPrompts.push("Imagine you owned a five star restaurant. What would you serve and what would the name of the restaurant be?");
		allPrompts.push("If you had the ability to do magic like the characters from Harry Potter, how would you use it?");
		allPrompts.push("If you had one million dollars to build anything you wanted, what would you build?");
	}
	
	function getAllPrompts() {
		if(!initialized) {
			populateAllPrompts();
			initialized = true;
		}
		
		return allPrompts;
	}
	
	function getRandomPrompts(count) {
		var prompts = getAllPrompts();
		var returnPrompts = [];
		
		for(var i = 0; i < count; i++) {
			var randomIndex = Math.floor(Math.random() * prompts.length);
			returnPrompts.push(prompts[randomIndex]);
		}
		
		return returnPrompts;
	}
	
	return {
		getAllPrompts: getAllPrompts,
		getRandomPrompts: getRandomPrompts
	}

})();